name = "elligator"
version = "0.1.0"
defaultTargets = ["Elligator"]
lintDriver = "batteries/runLinter"

[[lean_lib]]
name = "Elligator"

[[lean_exe]]
name = "elligator"
root = "Elligator"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "main"



[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
